language: c
script: make tests
compiler:
  - gcc
  - clang

sudo: true
before_install:
  - wget http://chipmunk-physics.net/release/ChipmunkLatest.tgz
  - tar xf ChipmunkLatest.tgz
  - cd Chipmunk7*
  - cmake -DBUILD_DEMOS=OFF .
  - sudo make install
